<?php

namespace AppBundle\Repository;

/**
 * AnimalCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
