<?php

namespace AppBundle\Repository;

/**
 * AnimalKindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalKindRepository extends \Doctrine\ORM\EntityRepository
{
}
