<?php

namespace AppBundle\Repository;

/**
 * OfferCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
