<?php

namespace AppBundle\Repository;

/**
 * UserDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
